/*
This file was generated by the following command:

cfunctions shift-jis-to-jis.c

*/
#ifndef CFH_SHIFT_JIS_TO_JIS_H
#define CFH_SHIFT_JIS_TO_JIS_H

#line 6 "shift-jis-to-jis.c"
int shift_jis_to_jis (const unsigned char* may_be_shift_jis, int* jis_first_ptr, int* jis_second_ptr);

#endif /* CFH_SHIFT_JIS_TO_JIS_H */
